/** 内置 API Key provider 展示名（id → 名称） */
export const PROVIDER_DISPLAY_NAMES: Record<string, string> = {
  anthropic: 'Anthropic',
  'ant-ling': 'Ant Ling',
  openai: 'OpenAI',
  'azure-openai-responses': 'Azure OpenAI',
  google: 'Google Gemini',
  deepseek: 'DeepSeek',
  nvidia: 'NVIDIA NIM',
  xai: 'xAI',
  groq: 'Groq',
  cerebras: 'Cerebras',
  openrouter: 'OpenRouter',
  'vercel-ai-gateway': 'Vercel AI Gateway',
  zai: 'ZAI',
  'zai-coding-cn': 'ZAI Coding (CN)',
  mistral: 'Mistral',
  minimax: 'MiniMax',
  'minimax-cn': 'MiniMax (CN)',
  moonshotai: 'Moonshot AI',
  'moonshotai-cn': 'Moonshot AI (CN)',
  huggingface: 'Hugging Face',
  fireworks: 'Fireworks',
  together: 'Together AI',
  opencode: 'OpenCode',
  'opencode-go': 'OpenCode Go',
  'kimi-coding': 'Kimi Coding',
  'cloudflare-workers-ai': 'Cloudflare Workers AI',
  'cloudflare-ai-gateway': 'Cloudflare AI Gateway',
  xiaomi: 'Xiaomi MiMo',
  'xiaomi-token-plan-cn': 'Xiaomi Token Plan (CN)',
  'xiaomi-token-plan-ams': 'Xiaomi Token Plan (AMS)',
  'xiaomi-token-plan-sgp': 'Xiaomi Token Plan (SGP)',
}

/** 设置页「API Key」区块展示的 provider（不含 OAuth / 云服务） */
export const API_KEY_PROVIDER_IDS = [
  'anthropic',
  'ant-ling',
  'openai',
  'google',
  'openrouter',
  'deepseek',
  'groq',
  'xai',
  'mistral',
  'nvidia',
  'zai',
  'zai-coding-cn',
  'minimax',
  'minimax-cn',
  'moonshotai',
  'moonshotai-cn',
  'huggingface',
  'fireworks',
  'together',
  'opencode',
  'opencode-go',
  'kimi-coding',
  'cerebras',
  'vercel-ai-gateway',
  'cloudflare-ai-gateway',
  'cloudflare-workers-ai',
  'xiaomi',
  'xiaomi-token-plan-cn',
  'xiaomi-token-plan-ams',
  'xiaomi-token-plan-sgp',
] as const

export const CUSTOM_PROVIDER_API_OPTIONS = [
  { value: 'openai-completions', label: 'OpenAI Completions' },
  { value: 'openai-responses', label: 'OpenAI Responses' },
  { value: 'anthropic-messages', label: 'Anthropic Messages' },
  { value: 'google-generative-ai', label: 'Google Generative AI' },
] as const
